# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

group = ExamGroup.find_or_create_by(name: '数学')
Member.find_or_create_by(exam_group_id: group.id, name: '芥川 和雄', study: '微分幾何,幾何解析・大域解析')
Member.find_or_create_by(exam_group_id: group.id, name: '遠藤 久顕', study: '位相幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '志賀 啓成', study: '複素解析')
Member.find_or_create_by(exam_group_id: group.id, name: '利根川 吉廣', study: '偏微分方程式, 幾何学的測度論')
Member.find_or_create_by(exam_group_id: group.id, name: '内藤 聡', study: '表現論')
Member.find_or_create_by(exam_group_id: group.id, name: '二宮 祥一', study: '確率論, 確率数値解析, 数理ファイナンス')
Member.find_or_create_by(exam_group_id: group.id, name: '本多 宣博', study: '複素幾何,微分幾何')
Member.find_or_create_by(exam_group_id: group.id, name: '柳田 英二', study: '偏微分方程式')
Member.find_or_create_by(exam_group_id: group.id, name: '山田 光太郎', study: '微分幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '磯部 健志', study: '幾何解析と変分問題')
Member.find_or_create_by(exam_group_id: group.id, name: 'KALMAN TAMAS', study: '位相幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '川平 友規', study: '複素力学系,複素解析')
Member.find_or_create_by(exam_group_id: group.id, name: '桒田 和正', study: '確率論,確率解析')
Member.find_or_create_by(exam_group_id: group.id, name: '鈴木 正俊', study: '解析的整数論')
Member.find_or_create_by(exam_group_id: group.id, name: '服部 俊昭', study: '幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '馬 昭平', study: '代数幾何')
Member.find_or_create_by(exam_group_id: group.id, name: '水本 信一郎', study: '保型関数論')
Member.find_or_create_by(exam_group_id: group.id, name: '米田 剛', study: '偏微分方程式,数理流体力学')
Member.find_or_create_by(exam_group_id: group.id, name: '斉藤 秀司', study: '数論幾何学,代数幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '梅原 雅顕', study: '微分幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '小島 定吉', study: 'トポロジー,幾何学,実験数学')
Member.find_or_create_by(exam_group_id: group.id, name: '西畑 伸也', study: '偏微分方程式論,非線形双曲型保存則, 流体の方程式')
Member.find_or_create_by(exam_group_id: group.id, name: '寺嶋 郁二', study: '微分位相幾何学,数理物理,数論的位相幾何学')
Member.find_or_create_by(exam_group_id: group.id, name: '三浦 英之', study: '偏微分方程式論')

group = ExamGroup.find_or_create_by(name: '基礎物理学')
Member.find_or_create_by(exam_group_id: group.id, name: '伊藤 克司', study: '素粒子論(超弦理論,超対称ゲージ理論,共形場理論)')
Member.find_or_create_by(exam_group_id: group.id, name: '今村 洋介', study: '素粒子論(弦理論と超対称ゲージ理論およびそれらの間の双対性)')
Member.find_or_create_by(exam_group_id: group.id, name: '岡眞', study: '原子核・ハドロン物理理論(強い相互作用,エキゾチックハドロン,ストレンジネス核物理)')
Member.find_or_create_by(exam_group_id: group.id, name: '河合 誠之', study: '宇宙物理学実験,X線・γ線・光学天文学(γ線バースト,ブラックホール等の衛星と地上からの観測,天体観測装置の開発)')
Member.find_or_create_by(exam_group_id: group.id, name: '久世 正弘', study: '高エネルギー物理学(加速器および非加速器素粒子実験;粒子の内部構造,レプトンとクォークの物理,ニュートリノ振動)')
Member.find_or_create_by(exam_group_id: group.id, name: '柴田 利明', study: '素粒子物理学の実験(陽子の中の反クォーク,陽子とクォークとグルーオンのスピン,陽子のスピンの謎の解明,量子色力学(QCD)の実験)')
Member.find_or_create_by(exam_group_id: group.id, name: '陣内 修', study: '高エネルギー素粒子物理実験(CERNLHC-ATLAS実験を用いたヒッグス粒子と超対称性粒子の研究)')
Member.find_or_create_by(exam_group_id: group.id, name: '宗宮 健太郎', study: '重力波望遠鏡KAGRAの設計と次世代型光干渉計の要素技術開発')
Member.find_or_create_by(exam_group_id: group.id, name: '中村 隆司', study: '原子核物理実験(不安定核ビームを用いた中性子過剰なエキゾチック核構造の研究,および天体核反応の研究)')
Member.find_or_create_by(exam_group_id: group.id, name: '山口 昌英', study: '宇宙論(素粒子的宇宙論,インフレーション宇宙,物質の起源,宇宙の相転移,重力理論)')
Member.find_or_create_by(exam_group_id: group.id, name: '堂谷 忠靖', study: 'X線天文学(X線衛星を用いた,中性子星や白色矮星,ブラックホールの観測的研究,衛星搭載用X線観測装置の開発)')
Member.find_or_create_by(exam_group_id: group.id, name: '肥山 詠美子', study: '原子核理論(厳密量子力学的3体・4体計算法を用いた原子核,ハイペロンを含む原子核の構造の研究)')
Member.find_or_create_by(exam_group_id: group.id, name: '松原 英雄', study: '赤外線天文学(星間物質,観測的宇宙論,銀河進化,衛星搭載用赤外線天体観測装置開発)機構')
Member.find_or_create_by(exam_group_id: group.id, name: '河野 俊之', study: '重イオンビームの医学利用,原子物理,放射線物理,放射線計測')

group = ExamGroup.find_or_create_by(name: '物性物理学')
Member.find_or_create_by(exam_group_id: group.id, name: '相川 清隆', study: '物性実験(原子・分子物理学,量子光学,レーザー冷却)')
Member.find_or_create_by(exam_group_id: group.id, name: '井澤 公一', study: '物性実験(異方的超伝導(超伝導対称性,準粒子励起構造,渦糸状態)量子限界点近傍の電子状態,低次元スピン系の熱輸送)')
Member.find_or_create_by(exam_group_id: group.id, name: '大熊 哲', study: '物性実験(低温物理,超伝導と電子局在,磁束状態,非平衡現象,低次元電子系,メゾスコピック系における量子物理現象の研究)')
Member.find_or_create_by(exam_group_id: group.id, name: '金森 英人', study: '物性実験(分子分光学,分子の空間捕捉と冷却,レーザーやマイクロ波を用いた量子コヒーレンス分光,励起状態分子のダイナミクス)')
Member.find_or_create_by(exam_group_id: group.id, name: '上妻 幹旺', study: '物性実験(レーザー冷却,中性原子気体のボース凝縮・フェルミ縮退,光格子中の冷却原子を使った量子シミュレーション)')
Member.find_or_create_by(exam_group_id: group.id, name: '古賀 昌久', study: '物性理論(強相関系/光格子冷却原子系,強相関電子系,低次元量子スピン系)')
Member.find_or_create_by(exam_group_id: group.id, name: '斎藤 晋', study: '物性理論(固体の電子構造,密度汎関数法と励起状態,クラスター,フラーレン,ナノチューブ,グラフェン)')
Member.find_or_create_by(exam_group_id: group.id, name: '笹本 智弘', study: '物性理論(統計物理学および数理物理学,特に非平衡統計力学,低次元輸送現象,ランダム系,厳密解等の解析的手法の開発)')
Member.find_or_create_by(exam_group_id: group.id, name: '竹内 一将', study: '物性実験(主に非平衡系の臨界現象と動力学,液晶対流,カオス)')
Member.find_or_create_by(exam_group_id: group.id, name: '田中 秀数', study: '物性実験(磁気相転移,量子磁気現象,低次元磁性,磁気励起,磁気共鳴,新物質開拓)')
Member.find_or_create_by(exam_group_id: group.id, name: '西田 祐介', study: '理論物理(主に冷却原子における量子多体系や少数系の物理,場の理論的手法の応用)')
Member.find_or_create_by(exam_group_id: group.id, name: '西森 秀稔', study: '物性理論(統計力学および量子力学の応用,特にスピングラス,相転移と臨界現象,量子アニーリングによる量子情報処理)')
Member.find_or_create_by(exam_group_id: group.id, name: '平原 徹', study: '物性実験(表面物理,ナノサイエンス,スピン物性,ディラック電子の物理,新奇な極薄物質の開拓)')
Member.find_or_create_by(exam_group_id: group.id, name: '藤澤 利正', study: '物性実験(低次元系量子輸送現象,電子・スピンのダイナミクス,メゾスコピック系の量子相関現象・量子情報素子)')
Member.find_or_create_by(exam_group_id: group.id, name: '松下 道雄', study: '物性実験(単一分子分光によるタンパク質の構造・機能相関の研究,発光を用いた単一スピンの観測と制御)')
Member.find_or_create_by(exam_group_id: group.id, name: '村上 修一', study: '物性理論(スピントロニクス,スピン輸送,トポロジカル相,幾何学的位相,量子物性)')
Member.find_or_create_by(exam_group_id: group.id, name: '吉野 淳二', study: '物性実験(半導体量子物性,半導体スピン物性,スピンエレクトロニクスの基礎,物質形成における表面ダイナミクス)')
Member.find_or_create_by(exam_group_id: group.id, name: '橋詰 富博', study: '物性実験(走査トンネル顕微鏡(STM)や走査プローブ顕微鏡(SPM)を用いたナノスケールデバイスの界面評価,生体材料計測,ナノスケール量子計測)')
Member.find_or_create_by(exam_group_id: group.id, name: '納富 雅也', study: '物性実験(フォトニックナノ構造(フォトニック結晶,プラズモニクス,メタマテリアル)における光物質相互作用制御の研究)')
Member.find_or_create_by(exam_group_id: group.id, name: '河村 徹', study: '高エネルギー密度プラズマ,レーザー/放電/イオンビーム生成プラズマ,非平衡プラズマ原子物理,輻射プラズマ流体力学,プラズマシミュレーション')
Member.find_or_create_by(exam_group_id: group.id, name: '平山 博之', study: '物性実験(固体表面・界面に局在する2次元電子系,表面ナノ構造への量子閉じ込め)')
Member.find_or_create_by(exam_group_id: group.id, name: '宗片比呂夫', study: '物性実験(光スピントロニクス,結晶成長,デバイス作製,磁性,光物性)')

group = ExamGroup.find_or_create_by(name: '化学')
group = ExamGroup.find_or_create_by(name: '地球惑星科学')
group = ExamGroup.find_or_create_by(name: '物質科学')
group = ExamGroup.find_or_create_by(name: '材料工学')
group = ExamGroup.find_or_create_by(name: '有機・高分子物質')
group = ExamGroup.find_or_create_by(name: '応用化学')
group = ExamGroup.find_or_create_by(name: '化学工学')
group = ExamGroup.find_or_create_by(name: '機械・制御情報系')
group = ExamGroup.find_or_create_by(name: '電気電子工学・電子物理工学')

group = ExamGroup.find_or_create_by(name: '通信情報工学')
Member.find_or_create_by(exam_group_id: group.id, name: '一色 剛', study: 'システム・オン・チップ設計技術,メディアプロ セッサ設計')
Member.find_or_create_by(exam_group_id: group.id, name: '上野 修一', study: '並列・VLSI計算論,量子・ナノ計算論')
Member.find_or_create_by(exam_group_id: group.id, name: '植松 友彦', study: '情報理論,符号理論,通信理論')
Member.find_or_create_by(exam_group_id: group.id, name: '尾形 わかは', study: '暗号理論,暗号プロトコル,情報セキュリティ')
Member.find_or_create_by(exam_group_id: group.id, name: '笠井 健太', study: '符号理論,LDPC符号,空間結合符号')
Member.find_or_create_by(exam_group_id: group.id, name: '高木 茂孝', study: '集積回路,回路網理論')
Member.find_or_create_by(exam_group_id: group.id, name: '高橋 篤司', study: 'VLSIレイアウト設計,同期回路')
Member.find_or_create_by(exam_group_id: group.id, name: '原 祐子', study: 'ハードウェア・ソフトウェア協調設計,高信頼組 込みシステム')
Member.find_or_create_by(exam_group_id: group.id, name: '府川 和彦', study: '移動通信,信号処理,無線ネットワーク')
Member.find_or_create_by(exam_group_id: group.id, name: '松本 隆太郎', study: '誤り訂正符号,情報理論,無線通信,量子通信')
Member.find_or_create_by(exam_group_id: group.id, name: '山岡 克式', study: '情報通信ネットワーク,インターネット')
Member.find_or_create_by(exam_group_id: group.id, name: '山田 功', study: '信号処理工学,最適化工学,逆問題')

group = ExamGroup.find_or_create_by(name: '土木工学')
group = ExamGroup.find_or_create_by(name: '建築学')
group = ExamGroup.find_or_create_by(name: '国際開発工学')
group = ExamGroup.find_or_create_by(name: '原子核工学')
group = ExamGroup.find_or_create_by(name: '分子生命科学')
group = ExamGroup.find_or_create_by(name: '生体システム')
group = ExamGroup.find_or_create_by(name: '生命情報')
group = ExamGroup.find_or_create_by(name: '生物プロセス')
group = ExamGroup.find_or_create_by(name: '生体分子機能工学')
group = ExamGroup.find_or_create_by(name: '物質科学創造')
group = ExamGroup.find_or_create_by(name: '物質電子化学')
group = ExamGroup.find_or_create_by(name: '材料物理科学')
group = ExamGroup.find_or_create_by(name: '環境理工学創造')
group = ExamGroup.find_or_create_by(name: '人間環境システム')
group = ExamGroup.find_or_create_by(name: '創造エネルギー')
group = ExamGroup.find_or_create_by(name: '化学環境学')
group = ExamGroup.find_or_create_by(name: '物理電子・物理情報')
group = ExamGroup.find_or_create_by(name: 'メカノマイクロ工学')

group = ExamGroup.find_or_create_by(name: '知能システム科学')
Member.find_or_create_by(exam_group_id: group.id, name: '寺野 隆雄', study: 'サービスサイエンスシステム制御系システム制御コース')
Member.find_or_create_by(exam_group_id: group.id, name: '室伏 俊明', study: '非加法的測度論,集合関数論,区分線形関数論,情報視覚化,形式概念分析')
Member.find_or_create_by(exam_group_id: group.id, name: '石井 秀明', study: 'システム制御,ネットワーク化制御,ハイブリッド制御,制御論における確率的アプローチ')
Member.find_or_create_by(exam_group_id: group.id, name: '新田 克己', study: '人工知能,論理プログラミング,ヒューマン・インタフェース,法情報学')
Member.find_or_create_by(exam_group_id: group.id, name: '高安 美佐子', study: '経済物理学,複雑ネットワーク,統計物理学,ビッグデータサイエンス')
Member.find_or_create_by(exam_group_id: group.id, name: '小長谷 明彦', study: 'バイオインフォマティクス,分子ロボティクス,バイオイメージング,高性能シミュレーション')
Member.find_or_create_by(exam_group_id: group.id, name: '出口 弘', study: '進化経済学,エージェントベースモデリング,社会システム論,社会シミュレーション言語開発(SOARS),経済・社会・組織シミュレーション,サービス科学')
Member.find_or_create_by(exam_group_id: group.id, name: '青西 亨', study: '非平衡統計力学,非線型動力学,生物物理学,計算論的神経科学')
Member.find_or_create_by(exam_group_id: group.id, name: '渡邊 澄夫', study: '確率論,数理統計,学習理論')
Member.find_or_create_by(exam_group_id: group.id, name: '樺島 祥介', study: '統計力学,情報理論,学習理論,神経回路網理論')
Member.find_or_create_by(exam_group_id: group.id, name: '瀧ノ上 正浩', study: '生物物理学,非線形非平衡科学,マイクロ流体工学,動的自己組織化システム,分子ロボット/人工細胞')
Member.find_or_create_by(exam_group_id: group.id, name: '三宅 美博', study: '共創システム(Co-creationSystem),コミュニケーション科学,認知神経科学,自己組織システム,ヒューマンインタフェース')
Member.find_or_create_by(exam_group_id: group.id, name: '小野 功', study: '進化計算,最適化,人工知能')
Member.find_or_create_by(exam_group_id: group.id, name: '中村 清彦', study: '脳情報科学,知能情報学,神経生理学,人工脳')
Member.find_or_create_by(exam_group_id: group.id, name: '宮下 英三', study: 'システム神経科学,生体運動制御,神経符号解読')
Member.find_or_create_by(exam_group_id: group.id, name: '山村雅幸', study: '機械学習,進化計算,バイオインフォマティクス,DNAコンピューティング')
Member.find_or_create_by(exam_group_id: group.id, name: '木賀 大介', study: '合成生物学,DNAコンピュータ,試験管内進化')
Member.find_or_create_by(exam_group_id: group.id, name: '中本 高道', study: 'ヒューマンインタフェース,嗅覚ディスプレイ,感性情報処理,センサ情報処理,匂いセンシングシステム、バイオセンサ')
Member.find_or_create_by(exam_group_id: group.id, name: '高村 大也', study: '計算言語学,自然言語処理,テキストマイニング')
Member.find_or_create_by(exam_group_id: group.id, name: '長谷川 晶一', study: 'バーチャルリアリティ,ヒューマンインタフェース,動力学シミュレーション,力触覚,エンタテインメント工学')
Member.find_or_create_by(exam_group_id: group.id, name: '長谷川 修', study: '人工脳SOINN,知能ロボティクス,実世界知能システム')
Member.find_or_create_by(exam_group_id: group.id, name: '金谷 泰宏', study: '公衆衛生,医療政策,健康危機管理(災害医療システム,感染制御システム)')
Member.find_or_create_by(exam_group_id: group.id, name: '齋藤 智也', study: 'バイオセキュリティ,公衆衛生危機管理,感染症疫学')
Member.find_or_create_by(exam_group_id: group.id, name: '木川 隆則', study: '生命動態システム,システム構造生物学,NMR,無細胞タンパク質合成,疎性モデリング')
Member.find_or_create_by(exam_group_id: group.id, name: '山田 誠二', study: 'ヒューマンエージェントインタラクション,知的インタラクティブシステム')
Member.find_or_create_by(exam_group_id: group.id, name: '柴田 崇徳', study: 'インテリジェンス,インタラクション,身体性,神経学的セラピー,脳機能,認知科学')
Member.find_or_create_by(exam_group_id: group.id, name: '本村 陽一', study: '大規模データモデリング,人間行動予測,生活支援技術,サービス工学,アクションリサーチ,ベイジアンネットワーク')
Member.find_or_create_by(exam_group_id: group.id, name: '矢野 和男', study: 'ビッグデータ解析,スマートシティ,ライフログ分析,統計物理/数理,知能増幅,社会行動分析')
Member.find_or_create_by(exam_group_id: group.id, name: '吉川 厚', study: 'ナレッジ・マネジメント,認知科学,ゲーム情報学,教育工学')

group = ExamGroup.find_or_create_by(name: '数理・計算科学')

group = ExamGroup.find_or_create_by(name: '計算工学')
Member.find_or_create_by(exam_group_id: group.id, name: '金子 晴彦', study: '【計算機システム・集積回路】統合符号化(データ圧縮,暗号化,誤り制御符号化),ディペンダブルシステム,高信頼ストレージシステム')
Member.find_or_create_by(exam_group_id: group.id, name: '吉瀬 謙二', study: '【計算機システム・集積回路】計算機アーキテクチャ(高速化,低消費電力化,性能検証,マルチプロセッサ,大規模システム,組み込みシステム)')
Member.find_or_create_by(exam_group_id: group.id, name: '小林 隆志', study: '【計算機ソフトウェア】ソフトウェア工学(ソフトウェア保守,プログラム解析,プログラム理解,開発支援ツール,ソフトウェア設計)')
Member.find_or_create_by(exam_group_id: group.id, name: '権藤 克彦', study: '【計算機ソフトウェア】ソフトウェア工学,ソフトウェア開発環境,プログラミング言語')
Member.find_or_create_by(exam_group_id: group.id, name: '佐伯 元司', study: '【計算機ソフトウェア】ソフトウェア工学(ソフトウェア設計論,要求工学,ソフトウェアプロセス,グループウェア)')
Member.find_or_create_by(exam_group_id: group.id, name: '西崎 真也', study: '【計算機ソフトウェア】プログラミング言語意味論,関数型言語,ソフトウェア検証')
Member.find_or_create_by(exam_group_id: group.id, name: '宮崎 純', study: '【計算機ソフトウェア】大規模コンピューティング,情報検索・情報推薦,ヒューマンインタフェース')
Member.find_or_create_by(exam_group_id: group.id, name: '横田 治夫', study: '【計算機ソフトウェア】データ工学(データベース,並列分散データ処理,高機能ストレージシステム,ディペンダブルシステム)')
Member.find_or_create_by(exam_group_id: group.id, name: '横田 理央', study: '【計算機ソフトウェア】高性能計算,大規模並列処理,N体アルゴリズム,流体解析,分子シミュレーション')
Member.find_or_create_by(exam_group_id: group.id, name: '渡部 卓雄', study: '【計算機ソフトウェア】形式手法,自己反映計算,並行計算,並列処理,プログラミング言語の設計と実装')
Member.find_or_create_by(exam_group_id: group.id, name: '秋山 泰', study: '【知能情報処理】バイオインフォマティクス,創薬支援コンピューティング,大規模並列処理応用,機械学習応用')
Member.find_or_create_by(exam_group_id: group.id, name: '石田 貴士', study: '【知能情報処理】データマイニング,バイオインフォマティクス,大規模データ解析,機械学習')
Member.find_or_create_by(exam_group_id: group.id, name: '井上 克巳', study: '【知能情報処理】人工知能(推論,知識表現,学習),論理プログラミング,マルチエージェントシステム,システム生物学')
Member.find_or_create_by(exam_group_id: group.id, name: '篠田 浩一', study: '【知能情報処理】音声・画像・映像の認識・理解,ヒューマン・コンピュータインタラクション,統計的パターン処理')
Member.find_or_create_by(exam_group_id: group.id, name: '徳永 健伸', study: '【知能情報処理】計算言語学,自然言語処理,知的情報アクセス')
Member.find_or_create_by(exam_group_id: group.id, name: '藤井 敦', study: '【知能情報処理】自然言語処理,情報検索,Webマイニング')
Member.find_or_create_by(exam_group_id: group.id, name: '村田 剛志', study: '【知能情報処理】人工知能,Webマイニング,リンクマイニング,社会ネットワーク分析')
Member.find_or_create_by(exam_group_id: group.id, name: '亀井 宏行', study: '【感覚・知覚情報処理】考古遺跡の物理探査,考古情報学(データマイニング,GIS応用)')
Member.find_or_create_by(exam_group_id: group.id, name: '小池 英樹', study: '【感覚・知覚情報処理】ヒューマン・コンピュータインタラクション,コンピュータビジョンとその応用,コンピュータグラフィックスと視覚化,セキュリティとユーザビリティ')
Member.find_or_create_by(exam_group_id: group.id, name: '齋藤 豪', study: '【感覚・知覚情報処理】コンピュータグラフィクス、画像処理、色彩工学、描画分析、描画ソフトウェア')

group = ExamGroup.find_or_create_by(name: '情報環境学(社会・環境系)')
group = ExamGroup.find_or_create_by(name: '人間行動システム')
group = ExamGroup.find_or_create_by(name: '価値システム')
group = ExamGroup.find_or_create_by(name: '経営工学')
group = ExamGroup.find_or_create_by(name: '社会工学')
group = ExamGroup.find_or_create_by(name: '技術経営')
